[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
cmds = ["npm install -g npm@latest"]

[phases.install]
cmds = ["npm config set update-notifier false", "cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npm run build"]

[start]
cmd = "node backend/dist/src/main"

[variables]
NODE_ENV = "production"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/loyalty?schema=public"
