export const API_VERSION = 'v1';
export const API_PREFIX = `/api/${API_VERSION}`;
export const POINTS = { DEFAULT_EXPIRY_DAYS: 365, MIN_REDEEM: 100, CHECKIN_BASE: 10, STREAK_BONUS_PER_DAY: 2, MAX_STREAK_BONUS: 50, REFERRAL_BONUS_REFERRER: 500, REFERRAL_BONUS_REFEREE: 250, BIRTHDAY_BONUS: 200 };
export const GAMIFICATION = { MAX_DAILY_CHECKINS: 1, LEADERBOARD_SIZE: 100, SPIN_WHEEL_COOLDOWN_HOURS: 24, MAX_ACTIVE_CHALLENGES: 5 };
export const AUTH = { ACCESS_TOKEN_EXPIRY: '15m', REFRESH_TOKEN_EXPIRY: '7d', PASSWORD_MIN_LENGTH: 8, MAX_LOGIN_ATTEMPTS: 5, LOCKOUT_DURATION_MINUTES: 30 };
export const RATE_LIMITS = { GLOBAL: { ttl: 60000, limit: 100 }, AUTH: { ttl: 60000, limit: 10 }, POINTS: { ttl: 60000, limit: 30 } };
export const IDENTITY = { FACE_MATCH_THRESHOLD: 0.85, LIVENESS_THRESHOLD: 0.90, ID_DOCUMENT_TYPES: ['PASSPORT', 'DRIVERS_LICENSE', 'NATIONAL_ID'], MAX_FACE_ENROLLMENT_ATTEMPTS: 3, VERIFICATION_EXPIRY_DAYS: 365 };
